"""任务契约层：8 字段契约、条件原语、运行结果。"""

from .conditions import (
    AllOf,
    Always,
    AnyOf,
    CallableCondition,
    Condition,
    ConditionResult,
    FeatureMatches,
    Never,
    NotCondition,
    StateIn,
    StateIs,
    all_of,
    any_of,
    build_popup_condition,
    callable_condition,
    feature,
    not_,
    predicate,
    state_in,
)
from .contract import (
    CONTRACT_FIELDS,
    FatalErrorSpec,
    RecoverableErrorSpec,
    TaskContract,
    TimeoutSpec,
)
from .outcome import DiagnosticEvent, TaskOutcome, TaskResult

__all__ = [
    "AllOf",
    "Always",
    "AnyOf",
    "CONTRACT_FIELDS",
    "CallableCondition",
    "Condition",
    "ConditionResult",
    "DiagnosticEvent",
    "FatalErrorSpec",
    "FeatureMatches",
    "Never",
    "NotCondition",
    "RecoverableErrorSpec",
    "StateIn",
    "StateIs",
    "TaskContract",
    "TaskOutcome",
    "TaskResult",
    "TimeoutSpec",
    "all_of",
    "any_of",
    "build_popup_condition",
    "callable_condition",
    "feature",
    "not_",
    "predicate",
    "state_in",
]
